 
        
         <header class=" clearfix bg">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">

            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <!-- <?php //if ($this->themeSetting('logo')): ?>
                <a href="<?php //echo $site->url(); ?>" class="site-title"><img
                        src="<?php //echo $this->themeSettingAssetUrl('logo'); ?>"  class="col-12" title="Logo"></a>
                <?php
//else: ?>
                <a href="<?php //echo $site->url(); ?>"
                    class="site-title"><?php //echo $this->pageTitle($site->title()); ?></a>
                <?php
//endif; ?> -->
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">

            </div>
        </div>
        
    </header>
    