<!--ccadena -->
<?php  $escape = $this->plugin('escapeHtml'); ?>
<?php  if (count($filters) > 0): ?>
<div class="search-filters">
    <?php  foreach ($filters as $filterLabel => $filterValues): ?>
    <div class="filter">
        <!-- <span class="filter-label"><?php  //echo $escape($filterLabel); ?></span> -->
        <?php  foreach ($filterValues as $filterValue): ?>
        <h2 ><?php  echo $escape($filterValue); ?></h2>
        <?php  endforeach; ?>
    </div>
    <?php  endforeach; ?>
</div>
<?php  endif; ?>
