<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title',
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier',
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label',
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created',
    ],
];
?>
<?php if ($itemSetShow): ?>

    <?php// echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <div class="item-set-items">
     <?php //cc echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
   <?php //echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif;?>


<h1>Discover</h2>
 
<div class="d-flex justify-content-between m-5">
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="btn btn-info btn m-1" role="button" href="/s/octoroon/item">All Items
</a>
  </li>
  <li class="nav-item">
    <a class="btn btn-info btn  m-1" href="/s/octoroon/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=8&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=Performances&resource_class_id%5B%5D=&item_set_id%5B%5D=&submit=Search">Performances
</a>
  </li>
  <li class="nav-item">
    <a class="btn btn-info btn m-1 " href="/s/octoroon/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=&resource_class_id%5B%5D=1&item_set_id%5B%5D=&submit=Search">People
</a>
  </li>
  <li class="nav-item">
    <a class="btn btn-info btn  m-1 " href="/s/octoroon/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=8&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=Places&resource_class_id%5B%5D=&item_set_id%5B%5D=&submit=Search">Places
 </a>
  </li>
  <li class="nav-item">
    <a class="btn btn-info btn  m-1" " href="/s/octoroon/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=8&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=Historic+Event&resource_class_id%5B%5D=&item_set_id%5B%5D=&submit=Search">Historic Events</a>
  </li>
    <li class="nav-item">
    <a class="btn btn-info btn m-1 " href="/s/octoroon/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=8&property%5B0%5D%5Btype%5D=in&property%5B0%5D%5Btext%5D=Article&property%5B1%5D%5Bjoiner%5D=or&property%5B1%5D%5Bproperty%5D=8&property%5B1%5D%5Btype%5D=in&property%5B1%5D%5Btext%5D=Prompt+Book&property%5B2%5D%5Bjoiner%5D=or&property%5B2%5D%5Bproperty%5D=8&property%5B2%5D%5Btype%5D=in&property%5B2%5D%5Btext%5D=Playbill&resource_class_id%5B%5D=&item_set_id%5B%5D=&submit=Search">Media</a>
  </li>
</ul>
    <div class="row">
        <div class="container">

      <?php echo $this->partial('common/search-form'); ?>
    </div>
</div>
      <?php  echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'btn btn-light m-1']); ?>
    

 </div>
 <?php   echo $this->searchFilters(); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
     <?php echo $this->sortSelector($sortHeadings); ?>
</div>
<?php $this->trigger('view.browse.before');?>
 <!-- **ccadena <ul class="resource-list"> -->
<div class="row">
<?php
/**
*    Return an elipsis given a string and a number of words
*/
function elipsis ($text, $words = 30) {
    // Check if string has more than X words
    if (str_word_count($text) > $words) {

        // Extract first X words from string
        preg_match("/(?:[^\s,\.;\?\!]+(?:[\s,\.;\?\!]+|$)){0,$words}/", $text, $matches);
        $text = trim($matches[0]);

        // Let's check if it ends in a comma or a dot.
        if (substr($text, -1) == ',') {
            // If it's a comma, let's remove it and add a ellipsis
            $text = rtrim($text, ',');
            $text .= '...';
        } else if (substr($text, -1) == '.') {
            // If it's a dot, let's remove it and add a ellipsis (optional)
            $text = rtrim($text, '.');
            $text .= '...';
        } else {
            // Doesn't end in dot or comma, just adding ellipsis here
            $text .= '...';
        }
    }
    // Returns "ellipsed" text, or just the string, if it's less than X words wide.
    return $text;
}

$description = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam ut placeat consequuntur pariatur iure eum ducimus quasi perferendis, laborum obcaecati iusto ullam expedita excepturi debitis nisi deserunt fugiat velit assumenda. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, blanditiis nostrum. Nostrum cumque non rerum ducimus voluptas officia tempore modi, nulla nisi illum, voluptates dolor sapiente ut iusto earum. Esse? Lorem ipsum dolor sit amet, consectetur adipisicing elit. A eligendi perspiciatis natus autem. Necessitatibus eligendi doloribus corporis quia, quas laboriosam. Beatae repellat dolor alias. Perferendis, distinctio, laudantium? Dolorum, veniam, amet!';


?>

 
 
 <?php
    foreach ($items as $item):
      $heading = $item->value($headingTerm, ['default' => $translate('[Untitled]')]);
      $body = $item->value($bodyTerm);
?>
	   <!-- **ccadena <li class="item resource"> -->
	  <div class="card-group col-md-6 col-lg-4 ">
	   <div class="card mb-4 shadow-sm in-call-out">
	    <div class="card-header " data-size="small">
	      <h2 class="m-4"> <?php echo $item->link($heading); ?></h2>
	    </div>
	   
       <div class="card-body">
	        <div class=" float-left mr-3">
	                <?php echo $item->linkRaw($this->thumbnail($item, 'medium')); ?>
	        </div>
        
          <div class="description">
              <?php 
              echo elipsis($body, 20);
              ?>
              <span>
                <?php  
                  echo $item->link('Learn More');
                ?>
              </span>
          </div>
            
        <br>
        <div class="d-flex justify-content-between align-items-center">
<div class="btn-group"><button class="btn btn-sm btn-outline-secondary" type="button"> <?php echo $item->link('View Item'); // Print a link to $item ?></button><button class="btn btn-sm btn-outline-secondary" type="button"> <a href="<?php echo $item->adminUrl('edit', 'edit'); // Print a link to the edit form for $item ?>" target="_blank">Edit</a> </button></div>
 </div>
</div><!--end body -->
    </div><!--end card -->
  </div><!--end col-md-4 -->
  <?php endforeach;?>
</div>
</div>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after');?>
<?php echo $this->pagination(); ?>
