<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
//$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>
 
 <div class="card-header " data-size="small">
     
    <?php
         echo $this->pageTitle($item->displayTitle(), 1); 
    ?>
</div>

<!--start in-call-out with image-->
<div class="in-call-out" data-info="in-call-out" data-size="large" data-category="" tabindex="0">   
      <div class="content">
        
        
            <?php 
            if (!$embedMedia && $itemMedia): 
            ?>
                
                    
                        <?php 
                        foreach ($itemMedia as $media): 
                        ?>
                        <figure>
                            <?php 
                                echo $media->render(); 
                            ?>
                        </figure>
                        
                        <?php 
                        endforeach; 
                        ?>
                   
            <?php 
            endif; 
            ?>

            <?php 
            if ($embedMedia && $itemMedia): 
            ?>
    
                <div class="media-embeds">
                    
                    <?php 
                    foreach ($itemMedia as $media):
                     echo $media->render();
                    endforeach;
                    ?>
                </div>
            <?php 
            endif; 
            ?>
            
            
            <?php 
                $this->trigger('view.show.map'); 
            ?> 
        
   
 
 
   
<!--end figure -->        
       
    <div class="content-area">
                <div>
                    <p tabindex="0">
                        <?php echo $item->displayValues(); ?>
                    </p>
                </div><!--end div -->

                <div class="property">
                    <?php 
                        $this->trigger('view.show.after'); 
                    ?> 
                </div>
    </div><!--end content-area -->
   
</div><!-- end content -->

</div><!-- end in-call-out with image -->

 
<!-- <h1>TEST@@@@@@@@@</h1> -->

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
