<?php
$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', ''); ?>
  
 
<?php //echo $this->pageTitle($media->displayTitle(), 2); ?>
 
<?php $this->trigger('view.show.before'); ?>
<?php echo $media->displayValues(); ?>
<div class="property">
    <h4 class="pb-1 mb-4 font-italic border-bottom">
                Media
    </h4>
</div>
​<picture class="m-3"><?php echo $media->render(); ?></picture>


<?php $this->trigger('view.show.after'); ?>

