<?php
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage):
?>
    
<?php endif; ?>

<!-- ccadena hide-submenu -->
<!-- <?php //if ($activePage): ?>
    <?php //if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php //echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php //endif; ?>-->
<?php //endif; ?> 

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
  
    <?php echo $this->content; ?>                            
    
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php //echo $this->sitePagePagination(); ?>
<?php endif; ?>
