<?php $escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width,
initial-scale=1'); $this->headTitle($this->setting('installation_title', 'Omeka
S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css',
'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/octoroon.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/bootstrap.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/popper.min.js'));
//$this->headScript()->prependFile($this->assetUrl('js/jquery.gsap.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/TweenMax.min.js'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js',
'Omeka')); $this->trigger('view.layout'); $title =
$this->pageTitle($site->title()); $userBar = $this->userBar(); $logo =
$this->themeSettingAssetUrl('logo'); if ($logo): $title = '<img src="' .
$this->escapeHtml($logo) . '">'; endif; ?>

 
 
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>
</head>

<?php echo $this->htmlElement('body'); ?>

<?php echo $userBar; ?>


<header id="main" class="bg-dark no-gutter bg">
           
<div class="container ">
    <nav class="navbar navbar-expand-lg navbar-dark static-top" > 
    <div class="container">
        <div class="col-3">
            <?php if ($this->themeSetting('logo')): ?>
                 <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
            <?php else: ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
            <?php endif; ?>
        </div>
        
        <div class="col-9">
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
    

            
             
        </div>
            </div>
             
        </nav>
    </div>

 
</header>
 
<?php if (strpos($_SERVER['REQUEST_URI'], 'home') !== false): ?>
<!--homeage if is called welcome  ---->

<div class="site-wrapper in-call-out ">
    <div class="site-wrapper-inner bg">
   
    <div class="nav-scroller py-1 mb-2">
        
        </div>
        <div class="cover-container">
            <?php //include ('_includes/header-home.phtml') ;?>
            <!--content pages ---->
            <main id="content" role="main" class="inner cover">
                <div class="container">
                    <?php echo $this->content; ?>
                    
                </div>
            </main>
            <!--end content pages ---->
            <?php include ('_includes/footer.phtml') ;?>
        </div>
    </div>
</div>
<!--end homepage - home -->
<?php
elseif (strpos($_SERVER['REQUEST_URI'], 'custom') !== false): ?>
 



<?php
else: ?>
<div id="all-content" class="site-wrapper">

        
    <div class="in-call-out ">

        <div class="container-fluid no-paddding ">
            <?php //include ('_includes/header.phtml') ;?>
        </div>    
            <!--content pages ---->
            <div class="container" >
            <main id="content" role="main" >
                <div class="container-fluid pt-3">
                    <?php echo $this->content; ?>
                </div>
            </main>
            <!--end content pages ---->
     
            <?php //include ('_includes/footer.phtml') ;?>
        </div>
    </div>
</div>
<?php
endif; ?>
 
<script>
 

console.clear();

var tween;
var mediaQuery = window.matchMedia("(min-width: 768px)");


document.querySelector(".toggle").addEventListener("click", doCoolStuff);

// Listen to changes on the viewport size
mediaQuery.addListener(createTween);


// Initialize the conditional tween on page load
createTween();



function doCoolStuff() {
	tween.reversed() ? tween.play() : tween.reverse();
}


function createTween() {
	console.log('hide toggle', mediaQuery.matches);
	// Clear any possible props
	TweenLite.set('.navigation', {clearProps:'all'});
	
	if(!mediaQuery.matches) {
		tween = TweenLite.from(".navigation", 1, {
			height: 0,
			paused: true,
			reversed: true
		});
	}
}
</script>
</body>

</html>